<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Heating_Ctx" Id="{4bda9e87-2e0e-4ad7-b58a-5d875d5d8cc4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Heating_Ctx
VAR_INPUT
	io		: Heating_Ctx_Io;
	hmi		: Heating_Ctx_Hmi;
	state	: Heating_Ctx_States;
	priv	: Heating_Ctx_Priv;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>