<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="_TankCtrl_State" Id="{88224b70-8e2c-4dd1-b671-286fc2c7cbb3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK _TankCtrl_State EXTENDS State
VAR
	_ctx			: REFERENCE TO TankCtrl_Ctx;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{ebf03ac0-584c-4f6b-b737-2733633e5ac8}">
      <Declaration><![CDATA[(*FB_Init is always available implicitly and it is used primarily for initialization.
The return value is not evaluated. For a specific influence, you can also declare the
methods explicitly and provide additional code there with the standard initialization
code. You can evaluate the return value.*)
METHOD FB_Init : BOOL
VAR_INPUT
	(* TRUE: the retain variables are initialized (reset warm / reset cold)*)
	bInitRetains	: BOOL;
	(* TRUE: the instance will be copied to the copy code afterward (online change)*)
	bInCopyCode	: BOOL;
	iStateList	: States.I_StateRepo;
	ctx			: REFERENCE TO TankCtrl_Ctx;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_ctx REF= ctx;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>