<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Tag" Id="{1f0098db-33f0-4898-a480-2525f8673171}" SpecialFunc="None">
    <Declaration><![CDATA[(*
TagBase with auto component registration.
*)
FUNCTION_BLOCK FINAL Tag EXTENDS TagBase
VAR
	_component		: Component(THIS^);	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>