<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="README" Id="{3b309d93-e896-46ad-ab92-d4eabab3ace1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM README]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
This is a template for a Domain object. Copy this folder to your project and rename its files to suit your application.
The 'ExampleDomain' domain is just a placeholder. You folder should be named e.g. 'ConveyorMgr' and then it should have the following structure:

ConveyorMgr
|
|-- Ctx
|   |-- Io
|   |   |-- ConveyorMgr_Io_In (STRUCT)
|   |   |-- ConveyorMgr_Io_Out (STRUCT)
|   |
|   |-- ConveyorMgr_Hmi (STRUCT)
|   |-- ConveyorMgr_Io (STRUCT)
|   |-- ConveyorMgr_Priv (STRUCT)
|   |-- ConveyorMgr_States (FB)
|
|-- State
|   |-- _ConveyorMgr_State (FB)
|   |-- ConveyorMgr_ExampleState (FB)
|
|-- Ui
|   |-- Visu
|   |
|   |-- ConveyorManager_StatusText (FB)
|
|-- ConveyorMgr (FB)
|-- ConveyorMgr_Ctx (STRUCT)

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>