<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Room_Ctx_Priv" Id="{f780ea0b-40f4-4a65-aec6-edfe7e6fb652}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Room_Ctx_Priv
VAR_INPUT
	bActive			: BOOL;
	bReady			: BOOL;
	
	iRequestEvent	: I_SignalEmit;
	bPaused			: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>