<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Outlet_State" Id="{7a304970-5f6e-42ae-af6e-b315b94ae50e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Outlet_State EXTENDS State
VAR
	_ctx			: REFERENCE TO Outlet_Ctx;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{6977f882-28ba-4158-9704-4e00d267def9}">
      <Declaration><![CDATA[(*FB_Init is always available implicitly and it is used primarily for initialization.
The return value is not evaluated. For a specific influence, you can also declare the
methods explicitly and provide additional code there with the standard initialization
code. You can evaluate the return value.*)
METHOD FB_Init : BOOL
VAR_INPUT
	(* TRUE: the retain variables are initialized (reset warm / reset cold)*)
	bInitRetains	: BOOL;
	(* TRUE: the instance will be copied to the copy code afterward (online change)*)
	bInCopyCode	: BOOL;
	iStateList	: States.I_StateRepo;
	ctx			: REFERENCE TO Outlet_Ctx;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_ctx REF= ctx;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>