<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{46c268e9-fb81-4ca2-9b53-e3c90b600c5e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	safety				: Safety<2>;
	heating				: Heating<40>;
	standardRoom		: ARRAY[1..5] OF TempTimeRoom;
	receptionRoom		: PassiveRoom;
	conferentionRoom01	: PassiveTempTimeRoom;
	conferentionRoom02	: PassiveTempTimeRoomWithMultipleValves<3>;
	storeRoom01			: TempRoom;
	storeRoom02			: TempRoomWithMultipleSensors<3>;
	
	bSimulation			: BOOL;
	
	dbgInfo				: DebugInfo;	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Runtime();
]]></ST>
    </Implementation>
    <Method Name="_IO" Id="{03b676de-555c-400e-bba5-4ba9784520ec}">
      <Declaration><![CDATA[METHOD PRIVATE _IO
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>