<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TankCtrl_States" Id="{44373ab6-a473-43ea-8549-265867885179}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TankCtrl_States
VAR_OUTPUT
	iEnabled		: I_Tag;
	iDisabled		: I_Tag;
	
	iFault			: I_Tag;
	iEStop			: I_Tag;;
	
	iFilling		: I_Tag;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>