<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Room_State_LowTemperature_Hmi" Id="{57d8e8ec-5944-41d3-b28b-9b0f6265864b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Room_State_LowTemperature_Hmi
VAR_OUTPUT PERSISTENT
	rHighTemperature	: LREAL := 20.0;
	rLowTemperature 	: LREAL := 19.0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>