<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="_ToDo" Id="{98d49df4-7f63-4c32-911d-1781c23c5b9e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL _ToDo
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
DESCRIPTION:
- _				DONE
- Arg			DONE 
- Broadcast		
- Callable		
- Dbg			DONE
- Ec
- Iter			DONE
- Result		DONE
- Runtime		DONR
- State
- Strings		DONE
- Tags			DONE
*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>