<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Room_State_DemandHeating_Hmi" Id="{bc6ae731-33fd-406b-8247-6ad114335f62}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Room_State_DemandHeating_Hmi
VAR_INPUT
	bDemandButton		: BOOL;
END_VAR
VAR_OUTPUT PERSISTENT
	nActivationTime			: UDINT := 30;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>