<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{46c268e9-fb81-4ca2-9b53-e3c90b600c5e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	safety				: Safety<CST.MAX_ESTOP>;
	heating				: Heating<CST.MAX_ROOM>;
	
	stdRoom				: ARRAY[1..3] OF StandardRoom;
	reception			: ReceptionRoom;

	dbgInfo				: DebugInfo;
	rtTick				: R_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[rtTick(CLK :=  Tick(sim.param.nTick), Q => sim.bTick);
sim.bTick := sim.bTick AND sim.param.bToggleSim;

Runtime();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>