<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="EntityExtend" Id="{b1b05739-2998-4df2-bd04-c0e688bec812}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EntityExtend IMPLEMENTS I_Debug
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{36ce8d10-34e1-43cd-a8e1-e04990476620}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)
	
	iEntity	: I_EntityNode;
END_VAR
VAR
	_nResult	: Result;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF IsErr(_ExtendEntity(iEntity), nOut => _nResult) THEN
	DebugMsg(THIS^, Tc2_Standard.CONCAT('_ExtendEntity(I_EntityNode) failed with code: ', ResultToStr(_nResult)));
END_IF]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>