<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="GetUnixTime" Id="{9256dbe0-970c-46b2-beb0-50dc80b906e9}" SpecialFunc="None">
    <Declaration><![CDATA[// Precision: 100ns.
FUNCTION GetUnixTime : ULINT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GetUnixTime := Tc2_System.F_GetSystemTime() - 11_644_473_600_000_000_0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>