<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Tank_States" Id="{05f6620d-c34f-4d1d-9326-43ff5194f5d1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Tank_States
VAR_OUTPUT
	iEnabled		: I_Tag;
	iDisabled		: I_Tag;
	iFill			: I_Tag;
	iFault			: I_Tag;
	iSystemOff		: I_Tag;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>