<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FloatArg" Id="{00911996-c08a-42e6-b802-f28bf17d1565}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FloatArg IMPLEMENTS I_MutFloatArg
VAR
	_val			: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Val" Id="{6d8da170-8112-482c-953b-21eacfd99080}">
      <Declaration><![CDATA[PROPERTY Val : LREAL
]]></Declaration>
      <Get Name="Get" Id="{d6a7f46b-4571-42d8-947d-f1572f1495d7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Val := _val;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{d2f51f5b-0ee9-40ab-898e-c4bd89ae55dc}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_val := Val;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>