<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="DebugList" Id="{489c56af-ae27-4926-af44-96228e2f35be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DebugList
VAR
	_refLen				: REFERENCE TO UDINT REF= _Debug.nDebugLen;
	_refList			: REFERENCE TO ARRAY[0..Param.DEBUG_CAP] OF ST_DebugInfo REF= _Debug.stDebug;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>