<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Room_State_Fault" Id="{a0562641-f5c5-4611-ac4d-a35e1468e2c4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Room_State_Fault EXTENDS Room_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>