<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ExampleDomain" Id="{2cc7bbb1-01ad-4ca5-8dec-c2ca30454bb0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ExampleDomain IMPLEMENTS I_DomainProvider, I_Execute
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR CONSTANT
	MAX_STATE		: UDINT := 1;
END_VAR
VAR
	exe				: Execute(THIS^);

	// Context
	ctx				: ExampleDomain_Ctx;

	// State Machine
	
	stateMachine	: StateMachine;
	stateRepo		: StateRepo<MAX_STATE>;
	stateBuffer		: StateBuffer<MAX_STATE>;
	stateMgr		: StateManager<MAX_STATE>(stateMachine, stateRepo, stateBuffer);
	A_Smgr			: A_StateManager(stateMgr, ctx.priv.smgr);
	
	// States
	
	example			: ExampleDomain_ExampleState(stateRepo, ctx);
	exampleAssign	: A_Tag(example.Tag, ctx.state.iExample);
	
	// FLAGS
	flagList		: FlagList<0>;
	
	// SIGNALS
	signalList		: SignalList<0>;
	
	// RECEIVERS
	receiverList	: ReceiverList<0>;
	
	// HMI
	statusText		: ExampleDomain_StatusText(ctx);
	
	// DOMAIN
	domTag			: Tag;
	domain			: Domain(domTag, stateMgr, flagList, signalList, receiverList);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Dom" Id="{622704c3-9cc2-4725-8570-455b354fa60e}">
      <Declaration><![CDATA[PROPERTY Dom : I_Domain]]></Declaration>
      <Get Name="Get" Id="{b38c86ed-180e-4b43-9a59-2077dac7971b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Dom := domain;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Execute" Id="{c897e5cf-559a-456a-a239-6e33a3deb831}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>