<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Room_Ctx_Hmi" Id="{9536c277-9786-455b-b876-b447754e1a8d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Room_Ctx_Hmi
VAR_INPUT
	nId						: UDINT;	

	sStatusText				: Str;
	sErrorText				: Str;
	nStatusColor			: Color;
	
	sData					: Str;
	
	bDisable				: BOOL;
	sDisableText			: Str;
	
	bReset					: BOOL;
	bHideReset				: BOOL;
END_VAR
VAR_OUTPUT PERSISTENT
	nTimeout				: UDINT := 1;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>