<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BinArg" Id="{cb0fcc97-6bd1-4da2-ad95-d55933bfe94a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BinArg IMPLEMENTS I_MutBinArg
VAR
	_val			: LWORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Val" Id="{561e9447-a720-49d7-897e-fa3dc653c48d}">
      <Declaration><![CDATA[PROPERTY Val : LWORD
]]></Declaration>
      <Get Name="Get" Id="{e19392a7-d96c-4409-af36-6659fa831215}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Val := _val;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{92426485-401c-4221-a784-58afae172b3e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_val := Val;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>