<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BoolArg" Id="{e27e2f24-10ad-4112-bcdb-e1d34b1a5e15}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BoolArg IMPLEMENTS I_MutBoolArg
VAR
	_val			: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Val" Id="{d9f2d2c0-a054-437f-8e42-b9057cb96059}">
      <Declaration><![CDATA[PROPERTY Val : BOOL
]]></Declaration>
      <Get Name="Get" Id="{d4d0bc75-0aba-4584-82fe-08f5e787da5e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Val := _val;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{f9b46fd3-d346-4048-a898-ec0e903786b6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_val := Val;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>