<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="StandardRoom" Id="{2e0e75c6-de15-4761-ae40-14041f36bdf4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK StandardRoom IMPLEMENTS I_Execute
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{51b956d4-c76f-41de-a458-174fed593c72}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>