<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Random" Id="{ef94bdce-8d7b-4e94-aee6-dfa953145eda}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Random : REAL
VAR_STAT
	_nSeed	: INT;
END_VAR
VAR
	_drand	: DRAND;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_drand(seed := _nSeed + 1);
Random := LREAL_TO_REAL(_drand.Num);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>