<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Tick" Id="{af0eb983-e1a9-488e-9880-a3e02be9a6ad}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Tick : BOOL
VAR_INPUT
	nTimeInMs	: ULINT;
	nTaskInMs	: ULINT := 20;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Tick := (GetSysTime() MOD (nTimeInMs * 10_000)) < (nTaskInMs * 10_000);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>