<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Room_Ctx_States" Id="{8120c9d6-f1d4-454c-bccd-a6a9cb566b32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Room_Ctx_States
VAR_OUTPUT
	iMgr			: I_StateManager;
	
	iSystemOff		: I_State;
	iFault			: I_State;
	iDisable		: I_State;
	iIdle			: I_State;
	iHeat			: I_State;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>