<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="_Room_State" Id="{df0168ad-9f27-4512-92eb-a0e2e652ad32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT _Room_State EXTENDS State
VAR
	_ctx	: REFERENCE TO Room_Ctx;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{3b81f292-3682-4c8e-9b1e-db90db2f1994}">
      <Declaration><![CDATA[(*FB_Init is always available implicitly and it is used primarily for initialization.
The return value is not evaluated. For a specific influence, you can also declare the
methods explicitly and provide additional code there with the standard initialization
code. You can evaluate the return value.*)
METHOD FB_Init : BOOL
VAR_INPUT
	(* TRUE: the retain variables are initialized (reset warm / reset cold)*)
	bInitRetains	: BOOL;
	(* TRUE: the instance will be copied to the copy code afterward (online change)*)
	bInCopyCode	: BOOL;
	ctx		: REFERENCE TO Room_Ctx;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_ctx REF= ctx;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>