<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Heating_Ctx_Priv" Id="{a4dbf3bc-91dd-4988-bf90-c6d789fe1a17}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Heating_Ctx_Priv
VAR_INPUT
	iActiveRoom		: I_Arg;
	nPassiveRooms	: UDINT;	
END_VAR
VAR_OUTPUT
	iOnEnable		: I_SignalEmit;
	iOnDisable		: I_SignalEmit;
	iOnPause		: I_SignalEmit;
	iOnResume		: I_SignalEmit;
	
	iQueue			: I_MutArgQueue;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>