<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{eb48f8ab-546d-4778-8336-8c39ddca1ed3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//ec_test_01				: Test_Ec_FillAndMove;
	//ec_test_02				: Test_Ec_FillAndCoalesce;
	//ec_test_03				: Test_Ec_CompCast;
	
	broadcast_test_01		: Test_Broadcast_FillAndMove;
	broadcast_test_02		: Test_Broadcast_FillAndCoalesce;
	
	strings_test_01			: Test_Strings_WildcardCmp;

	debugInfo				: StageCore.DebugInfo;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Runtime();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>