<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AbstractReceiver" Id="{c46f739c-8b3f-4cdd-8554-e44831648382}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT AbstractReceiver IMPLEMENTS I_Callable, I_Receiver
VAR
	_tag: Tag;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Call" Id="{7bd0ae8b-60bb-4ea9-8cdc-b0909f6a307e}">
      <Declaration><![CDATA[(*
This method provides a standardized way for other objects to interact with the object that owns it.
*)
METHOD Call
VAR_INPUT
	iArg	: I_Arg;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Receive" Id="{952bece5-ce03-46c2-9fe8-6d4fb98ee01d}">
      <Declaration><![CDATA[METHOD INTERNAL Receive
VAR_INPUT
	iArg			: I_Arg;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Call(iArg);]]></ST>
      </Implementation>
    </Method>
    <Property Name="Tag" Id="{bf34ea37-dbe0-4dda-85a8-706b9379267c}">
      <Declaration><![CDATA[(*
Provides access to the tag associated with the signal.
*)
PROPERTY FINAL Tag : I_Tag]]></Declaration>
      <Get Name="Get" Id="{904ebb0a-3e09-4e22-b46c-582b44ddc0fb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Tag := _tag;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>