<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TagOption" Id="{e083b492-1776-450f-9367-b54d8276adc9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TagOption
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{df863cb7-3719-48f3-b333-1826b9ceace9}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)
	refTag		: REFERENCE TO Tag;
	sOption		: Strings.Str;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[refTag.Option := sOption;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>