<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TagOwner" Id="{9c425f65-2eaa-48f8-ae7a-4e0b35161a36}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TagOwner IMPLEMENTS I_TagOwner;
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Self" Id="{e4e76ef9-3c31-481e-89f1-7110d535e1cb}">
      <Declaration><![CDATA[PROPERTY Self : I_TagOwner]]></Declaration>
      <Get Name="Get" Id="{9359da33-4dcd-43b7-bcc6-ebeebb11763b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Self := THIS^;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>