<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BuildArgb" Id="{4422573d-a188-41ba-aa6d-067e8c958c7d}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	Returns raw RGBA value from components.
*)
FUNCTION BuildArgb : Argb
VAR_INPUT
	nRed: USINT;
	nGreen: USINT;
	nBlue: USINT;
	nAlpha: USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[BuildArgb := USINT_TO_UDINT(nBlue) OR
			SHL(USINT_TO_UDINT(nGreen), 8) OR
			SHL(USINT_TO_UDINT(nRed), 16) OR
			SHL(USINT_TO_UDINT(nAlpha), 24);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>